### ISSUE TITLE
per-minute consumption?

### ISSUE THREAD

**Issue by dulitz** [dacmanj/hubitat-moenflo#1]
The [pyflowater](https://github.com/rsnodgrass/pyflowater/blob/master/pyflowater) API claims to support minutely consumption queries, but I can't get that to work. I notice you use hourly as well, which I can get to work using pyflowater.

Do you have any news about whether an interval of "1m" can be used to query historical consumption?

**Comment by dacmanj** [comment]
Hi @dulitz, I think that's a mistake in pyflowater. If I send "[1m](https://github.com/rsnodgrass/pyflowater/blob/79f27309a3c825f3e29fbbf1d58127fbe6f5d39d/pyflowater/const.py#L35)" as a parameter to [water/consumption](https://github.com/rsnodgrass/pyflowater/blob/79249cc3391a0d6f8d75635615a1e10a5813e6a9/pyflowater/__init__.py#L301) using Postman, I get data aggregated into months not minutes.

David

**Comment by dulitz** [comment]
You're absolutely right, that's what's happening. I tried various options for minutely and they all got error returns. I'll submit a pull request to fix the name of the constant. Thanks.
